name: Deploy to Azure
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted  # <--- CRITICAL: This tells it to use YOUR VM
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and Push Docker Image
        run: |
          # 1. Get the ACR Name dynamically
          ACR_NAME=$(az acr list -g student-devops-rg --query "[0].name" -o tsv)
          
          # 2. Login to ACR
          az acr login --name $ACR_NAME
          
          # 3. Build the image
          docker build -t $ACR_NAME.azurecr.io/myapp:${{ github.sha }} .
          
          # 4. Push the image
          docker push $ACR_NAME.azurecr.io/myapp:${{ github.sha }}

      - name: Deploy to Kubernetes (AKS)
        run: |
          # 1. Get AKS Credentials
          AKS_NAME=$(az aks list -g student-devops-rg --query "[0].name" -o tsv)
          az aks get-credentials -g student-devops-rg -n $AKS_NAME --overwrite-existing
          

          # 3. Deploy
          kubectl create deployment myapp --image=$ACR_NAME.azurecr.io/myapp:${{ github.sha }} --dry-run=client -o yaml | kubectl apply -f -