name: Deploy to Azure
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted  # <--- This uses YOUR Azure VM!
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and Push Docker Image
        run: |
          ACR_NAME=$(az acr list -g student-devops-rg --query "[0].name" -o tsv)
          az acr login --name $ACR_NAME
          docker build -t $ACR_NAME.azurecr.io/myapp:${{ github.sha }} .
          docker push $ACR_NAME.azurecr.io/myapp:${{ github.sha }}

      - name: Deploy to Kubernetes (AKS)
        run: |
          AKS_NAME=$(az aks list -g student-devops-rg --query "[0].name" -o tsv)
          az aks get-credentials -g student-devops-rg -n $AKS_NAME --overwrite-existing
          #ACR_NAME=$(az acr list -g student-devops-rg --query "[0].name" -o tsv)
         # az aks update -n $AKS_NAME -g student-devops-rg --attach-acr $ACR_NAME
          kubectl create deployment myapp --image=$ACR_NAME.azurecr.io/myapp:${{ github.sha }} --dry-run=client -o yaml | kubectl apply -f -
